# Welcome to Handwritten Digit Recognition Project

## Importing Libraries

In [1]:
import numpy as np
import tensorflow as tf
from keras.preprocessing.image import ImageDataGenerator

## Preprocessing Training Dataset

In [2]:
train_datagen = ImageDataGenerator(rescale = 1./255,
                                   shear_range = 0.2,
                                   zoom_range = 0.2,
                                   horizontal_flip = True)
training_set = train_datagen.flow_from_directory('dataset/training_set',
                                                 target_size = (64,64),
                                                 batch_size = 32,
                                                 class_mode = 'categorical')

Found 1500 images belonging to 10 classes.


## Preprocessing Test Dataset

In [3]:
test_datagen = ImageDataGenerator(rescale = 1./255)
test_set = test_datagen.flow_from_directory('dataset/test_set',
                                            target_size = (64,64),
                                            batch_size = 32,
                                            class_mode = 'categorical')
#,class_mode = 'categorical'

Found 300 images belonging to 10 classes.


## Creating a Model

### Initialising the CNN

In [4]:
cnn = tf.keras.models.Sequential()

### Step 1 - Convolution

In [5]:
cnn.add(tf.keras.layers.Conv2D(filters=32, kernel_size=3, activation='relu',input_shape=(64,64,3)))

### Step 2 - Pooling

In [6]:
cnn.add(tf.keras.layers.MaxPool2D(pool_size=(2,2), strides = 2))

### Adding a second convolutional layer

In [7]:
cnn.add(tf.keras.layers.Conv2D(filters=32, kernel_size=3, activation='relu'))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=(2,2), strides = 2))

### Step 3 - Flattening

In [8]:
cnn.add(tf.keras.layers.Flatten())

### Step 4 - Full Connection

In [9]:
cnn.add(tf.keras.layers.Dense(units=128,activation='relu'))

### Step 5 - Output Layer

In [10]:
cnn.add(tf.keras.layers.Dense(units=10,activation='softmax'))

## Training the Model

### Compiling the CNN

In [11]:
cnn.compile(optimizer='adam', loss="categorical_crossentropy", metrics=['accuracy'])
#tf.keras.losses.CategoricalCrossentropy(from_logits=True)

### Training the CNN on the Training set and evaluating it on the Test set

In [12]:
cnn.fit(x=training_set, validation_data=test_set, epochs=25)

Epoch 1/25
47/47 [==============================] - 9s 181ms/step - loss: 2.3097 - accuracy: 0.1249 - val_loss: 2.1615 - val_accuracy: 0.2600
Epoch 2/25
47/47 [==============================] - 7s 150ms/step - loss: 1.8712 - accuracy: 0.3746 - val_loss: 2.0358 - val_accuracy: 0.2633
Epoch 3/25
47/47 [==============================] - 7s 154ms/step - loss: 1.5699 - accuracy: 0.4804 - val_loss: 1.8844 - val_accuracy: 0.2933
Epoch 4/25
47/47 [==============================] - 8s 161ms/step - loss: 1.4520 - accuracy: 0.5135 - val_loss: 1.6035 - val_accuracy: 0.4700
Epoch 5/25
47/47 [==============================] - 7s 156ms/step - loss: 1.2877 - accuracy: 0.5707 - val_loss: 1.4132 - val_accuracy: 0.5100
Epoch 6/25
47/47 [==============================] - 8s 161ms/step - loss: 1.0874 - accuracy: 0.6473 - val_loss: 1.2112 - val_accuracy: 0.6067
Epoch 7/25
47/47 [==============================] - 7s 156ms/step - loss: 0.9156 - accuracy: 0.6922 - val_loss: 1.0159 - val_accuracy: 0.7567
Epoch 

### Making single prediction

In [13]:
import numpy as np
from keras.preprocessing import image
import tensorflow as tf
import tkinter as tk
from tkinter import *
import win32gui
from PIL import ImageGrab, Image



In [43]:
img = image.load_img('dataset/single_prediction/7.png', target_size = (64, 64))
img = image.img_to_array(img)
img =  img/255.0
img = np.expand_dims(img, axis = 0)  
result = cnn.predict(img)
np.argmax(result)
#img

7

## Creating GUI for input

In [39]:
def predict_digit(img):
    img = img.resize((64,64))
    img = image.img_to_array(img)
    img = img/255.0
    img = np.expand_dims(img, axis = 0)  
    result = cnn.predict(img)
    return np.argmax(result),max(result)
   

In [40]:
class App(tk.Tk):
    def __init__(self):
        tk.Tk.__init__(self)

        self.x = self.y = 0

        # Creating elements
        self.canvas = tk.Canvas(self, width=300, height=300, bg = "white", cursor="cross")
        self.label = tk.Label(self, text="Thinking..", font=("Helvetica", 48))
        self.classify_btn = tk.Button(self, text = "Recognise", command =         self.classify_handwriting) 
        self.button_clear = tk.Button(self, text = "Clear", command = self.clear_all)

        # Grid structure
        self.canvas.grid(row=0, column=0, pady=2, sticky=W, )
        self.label.grid(row=0, column=1,pady=2, padx=2)
        self.classify_btn.grid(row=1, column=1, pady=2, padx=2)
        self.button_clear.grid(row=1, column=0, pady=2)

        #self.canvas.bind("<Motion>", self.start_pos)
        self.canvas.bind("<B1-Motion>", self.draw_lines)

    def clear_all(self):
        self.canvas.delete("all")

    def classify_handwriting(self):
        HWND = self.canvas.winfo_id() # get the handle of the canvas
        rect = win32gui.GetWindowRect(HWND) # get the coordinate of the canvas
        im = ImageGrab.grab(rect)

        digit, acc = predict_digit(im)
        self.label.configure(text= str(digit))

    def draw_lines(self, event):
        self.x = event.x
        self.y = event.y
        r=8
        self.canvas.create_oval(self.x-r, self.y-r, self.x + r, self.y + r, fill='black')

#root = tk()
app = App()
mainloop()

In [57]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [58]:
x= np.expand_dims(x,axis=0)


In [59]:
x

array([[[1, 2],
        [3, 4]]])

In [62]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [63]:
x= np.expand_dims(x,axis=1)
x

array([[[1, 2]],

       [[3, 4]]])